### POST print job
// Endpoint para impresión generica
POST {{ server }}/print/?printer={{name_system}}&type=ethernet
Content-Type: application/json

[
    {
        "properties": {
            "blockWidth": 48
        },
        "data": [
            {
                "styles": {
                    "$img": {
                        "align": "center",
                        "width": 300,
                        "height": 150
                    }
                },
                "imgPath": "/home/socamaru/Descargas/logos/ananau.png"
            },
            {
                "styles": {
                    "$qr": {
                        "align": "center"
                    }
                },
                "qr": {
                    "type": "img",
                    "data": "20450523381|01|F001|00000006|0|9.00|30/09/2019|6|sdfsdfsdf|"
                }
            },
            {
                "nColumns": 3,
                "styles": {
                    "1": {
                        "align": "center"
                    },
                    "total": {
                        "align": "right"
                    }
                },
                "rows": [
                    [
                        "cell 1",
                        "cell 2",
                        "cell 3"
                    ],
                    [
                        "123456789112345678921234567893123456789412",
                        {
                            "text": "second cell",
                            "class": "total"
                        }
                    ],
                    "secod row"
                ]
            }
        ]
    },
    {
        "properties": {
            "blockWidth": 48
        },
        "data": [
            {
                "styles": {
                    "$img": {
                        "align": "center",
                        "width": 300,
                        "height": 150
                    }
                },
                "imgPath": "/home/socamaru/Descargas/logos/ecotur.png"
            },
            {
                "styles": {
                    "$qr": {
                        "align": "center"
                    }
                },
                "qr": {
                    "type": "img",
                    "data": "20450523381|01|F001|00000006|0|9.00|30/09/2019|6|sdfsdfsdf|"
                }
            },
            {
                "nColumns": 3,
                "styles": {
                    "1": {
                        "align": "center"
                    },
                    "total": {
                        "align": "right"
                    }
                },
                "rows": [
                    [
                        "cell 1",
                        "cell 2",
                        "cell 3"
                    ],
                    [
                        "123456789112345678921234567893123456789412",
                        {
                            "text": "second cell",
                            "class": "total"
                        }
                    ],
                    "secod row"
                ]
            }
        ]
    }
]

### PUT reprint jobs
// Reimprime elementos de la cola de impresión
PUT {{ server }}/print/queue

### DELETE release print jobs
// Libera la cola de impresión
DELETE {{ server }}/print/queue

### GET queue size
// Obtiene elementos en cola
GET {{ server }}/print/queue

### Post  tickets to print
// Envia una boleta al servidor de impresion
POST {{ server }}/printer/ticket
Content-Type: application/json

[
  {
    "type": "invoice",
    "times": 1,
    "printer": {
      "type": "{{type}}",
      "name_system": "{{name_system}}",
      "port": "9100"
    },
    "data": {
      "business": {
        "comercialDescription": { "type": "text", "value": "PRIMER TICKET" },
        "description": "EMPRESA DE TRANSPORTE ECOTURISMO NACIONAL S.R.L.",
        "additional": [
          "RUC 20605333932 AGENCIA ANDAHUAYLAS",
          "DIRECCIÓN: AV. J. MARIA ARGUEDAS NRO. 414 ANDAHUAYLAS - ANDAHUAYLAS - APURIMAC",
          "TELÉFONO: 970005003"
        ]
      },
      "document": "TICKET DE VIAJE",
      "documentId": "002-29",
      "customer": ["ADQUIRIENTE", " DNI: 73354140", " PALOMINO PACO ROCIO"],
      "items": [
        {
          "description": [
            "Ruta: ANDAHUAYLAS-ABANCAY",
            "Embarque: SAN JERONIMO",
            "Destino: HUANCARAMA",
            "Asiento: 2    , DNI: 73354140",
            "Pasajero: PALOMINO PACO ROCIO",
            "F. Viaje : 14/06/2024 01:00 PM"
          ],
          "quanty": null,
          "unitPrice": null,
          "totalPrice": "20.00"
        }
      ],
      "amounts": { "Total": "20.00" },
      "additional": [
        "MONEDA: SOLES",
        "FORMA PAGO: Contado PEN 20.00",
        "F. EMISIÓN: 14/06/2024 12:51:30",
        "USUARIO: BETSABE - ANDA02"
      ],
      "finalMessage": null,
      "stringQR": null
    }
  },
  {
    "type": "invoice",
    "times": 1,
    "printer": {
      "type": "{{type}}",
      "name_system": "{{name_system}}",
      "port": "9100"
    },
    "data": {
      "business": {
        "comercialDescription": { "type": "text", "value": "SEGUNDO TICKET" },
        "description": "EMPRESA DE TRANSPORTE ECOTURISMO NACIONAL S.R.L.",
        "document": "RUC",
        "documentNumber": "20605333932"
      },
      "document": "Control de",
      "documentId": "002-29",
      "additional": [
        "F. EMISIÓN: 14/06/2024 12:51 PM",
        "USUARIO: BETSABE - ANDA02"
      ],
      "items": [
        {
          "description": [
            "Embarque: SAN JERONIMO",
            "Destino: HUANCARAMA",
            "Asiento: 2    , DNI: 73354140",
            "Pasajero: PALOMINO PACO ROCIO",
            "Bus: TOYOTA HIACE, Placa: BZU-412",
            "NAVEROS LIZUNDI CRISHTIAN"
          ],
          "totalPrice": "20.00"
        }
      ],
      "finalMessage": ["*** CONTROL DE BUS ***"]
    }
  }
]


### DELETE all tickets
// Elimina todos los tickets de la base de datos
DELETE {{ server }}/printer/ticket

### DELETE tickets before specific day
// Elimina tickets anteriores a una fecha dada
DELETE {{ server }}/printer/ticket?date=2024-02-11 13:02:43

### PRINT REPORT
POST {{ server }}/printer/report
Content-Type: application/json

{
  "printer": {
    "name_system": "{{ name_system }}",
    "port": 9100,
    "type": "{{ type }}",
    "properties": {
      "width": 42
    }
  },
	"title": "Varias tablas a imprimir",
	"tables": [
		{
			"title": "tabla 1",
			"body": [
				["item 1", "item 2", "item 3"],
				["item 1", "item 2", "item 3"],
				["item 1", "item 2", "item 3"],
				["item 1", "item 2", "item 3"]
			]
		},
		{
			"title": {
			  "text": "tabla 2",
			  "decorator": "*"
			},
			"separator": "|",
			"cellBodyStyles": {
				"0": "center"
			},
			"body": [
				[
				    "item 4",
					"item 5"
				],
				["Item 6", "Item 7", "Item 8", "Item 9"],
				["Item 1"],
				["","", "", "Esta es una frase multilinea"]
			]
		}
	]
}


### GET  connection server print
// Verifica el estado de conexion con el servidor de impresion
GET {{ server }}/test-connection
