name: jDeploy CI with Maven

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build App Installer Bundles GITHUB
        uses: shannah/jdeploy@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
      - name: Build App Installer Bundles NPM
        uses: shannah/jdeploy@master
        with:
          deploy_target: npm
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ secrets.GH_TOKEN }}
