name: jDeploy CI with Maven

on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Publish App Installer Bundles GITHUB
        uses: shannah/jdeploy@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}


