name: jDeploy CI with Maven

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v4
        with:
          name: target
          path: target

  publish_github:
    needs: [ build ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: target
          path: target
      - name: Publish App Installer Bundles GITHUB
        uses: shannah/jdeploy@master
        with:
          github_token: ${{ github.token }}

  publish_npm:
    needs: [ build ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: target
          path: target
      - name: Publish App Installer Bundles NPM
        uses: shannah/jdeploy@master
        with:
          deploy_target: npm
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ github.token }}
